### PR TITLE
Added moving_avg_from_stream.cpp and removed java equivelent

### PR DESCRIPTION
**Pull request by MeridjaNassim**

### CODE REVIEW

**Comment by MeridjaNassim** [comment]
is it possible that you add the "hacktoberfest-accepted" label to my PR

**Comment by MeridjaNassim** [comment]
I apologize for bothering you but, I think the label should be "hacktoberfest-accepted" with a 'hyphon' (-), since it wasn't accepted for my hacktoberfest.
Sorry again for bothering.

**Comment by shubhangi-singh21** [comment]
> I apologize for bothering you but, I think the label should be "hacktoberfest-accepted" with a 'hyphon' (-), since it wasn't accepted for my hacktoberfest.
> Sorry again for bothering.

The PR label anyways doesn't matter until the issue itself has the "hacktoberfest" label. If you still face any issue after the 14 days review period, feel free to let me know :)

**Comment by MeridjaNassim** [comment]
Agreed, thank you so much for your time :), I will be happy to contribute more to your project in the future.

**Pull request merged**
